### ISSUE TITLE
 invalid_grant error

### ISSUE THREAD

**Issue by FFXIV14** [MrPowerScripts/reddit-karma-farming-bot#155]
prawcore.exceptions.OAuthException: invalid_grant error processing request.

No clue. Worked yesterday, today it doesn't.

**Comment by FFXIV14** [comment]
Is there any follow up here or is this project essentially dead?

**Comment by Katvios** [comment]
People do have lives. You're welcome to fork and write a "follow up" yourself if you were so inclined. I'm sure other users would be delighted at your generosity. 

As the name suggests, there is a problem with authentication. Check that your credentials config is correct. Also, if the account has 2FA enabled, the bot will need an extra 2FA token.

Seeing that you've provided no code and only one line of traceback, I can't give any further insight.

**Comment by FFXIV14** [comment]
Would if I could my dude :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EliteDaMyth** [comment]
@Katvios It is better to not comment, if you do not have anything useful to say. Your comment did absolutely no good in helping solving the issue.

**Comment by Katvios** [comment]
@EliteDaMyth That is funny, because the poster deleted his second comment demanding a "follow up" to the project. 

If you somehow missed it, I did provide some suggestions with what little information he supplied. Before you chide me for doing "absolutely no good", keep in mind that this poster has provided next to nothing - no full tracebacks or code to go on. 

If you believe that you can post more useful suggestions with one line of error, then I fully encourage you to do so.

**Comment by FFXIV14** [comment]
@Katvios Sorry about only posting one line of code. I was trying to show the person who wrote it what/where it errored. I am not a programmer. I was only looking for help. Apologies if I submitted it wrong with not enough information or came across as demanding. Was not my intention

**Comment by MrPowerScripts** [comment]
Alright I think everyone was trying to be helpful here. Let's assume there was good intentions all around. This is likely an issue with the envars you provided. I would suggest reviewing those again as @Katvios pointed out. I don't think it's an issue with the bot itself.
